---
title: "CV"
sidebar: false
---

:::{style="text-align: right"}
My full CV is [**here**](https://nataliaguzzo.github.io/cv/guzzo-cv.pdf).
:::

### Education

- PhD in Linguistics (Letras – Language Studies, Linguistic Theory and Analysis)
    * Universidade Federal do Rio Grande do Sul (2011 – 2015)

- Graduate Research Trainee
    * McGill University (2014)

- Visiting researcher
    * University of Delaware (2013)

- MA in Language, Culture and Regionality
    * Universidade de Caxias do Sul (2008 – 2010)

- Licenciatura em Letras (Portuguese/English languages and literature)
    * Universidade de Caxias do Sul (2004 – 2008)


### Employment

- 2023-present: Professionnelle de recherche (lab coordinator)
    * Speech and Hearing Neurosciences Laboratory, Centre de recherche CERVO, Université Laval 

- 2023-present: Chargée de cours (lecturer)
    * Département de langues, linguistique et traduction, and École de langues, Université Laval 

- 2021-2023: Instructor; Assistant Professor (LTA)
    * Program in Linguistics, Saint Mary's University

- 2018-2020: Lecturer
    * Department of Linguistics, McGill University

- 2018-2019: Postdoctoral Researcher
    * Department of Linguistics, McGill University
  
- 2015-2017: Postdoctoral Research Assistant
    * Department of Linguistics, McGill University

- 2017: Chargée de cours (lecturer)
    * Départment de linguistique, Université du Québec à Montréal




***
